packages:
  - 'apps/*'
  - 'packages/*'
  - 'tools/*'

catalog:
  "@ai-sdk/anthropic": "^3.0.78"
  "@ai-sdk/google": "^3.0.75"
  "@ai-sdk/openai": "^3.0.64"
  "@ai-sdk/togetherai": "^2.0.51"
  "@vitest/coverage-v8": "^4.1.6"
  "@vitest/expect": "^4.1.6"
  "ai": "^6.0.184"
  "es-toolkit": "^1.46.1"
  "tsup": "^8.5.1"
  "tsx": "^4.21.0"
  "vitest": "^4.1.6"
  "zod": "^4.4.3"
