packages:
  - 'apps/*'
  - 'packages/*'
  - 'tools/*'

catalog:
  "@ai-sdk/anthropic": "^3.0.50"
  "@ai-sdk/google": "^3.0.34"
  "@ai-sdk/openai": "^3.0.37"
  "@ai-sdk/togetherai": "^2.0.35"
  "@vitest/coverage-v8": "^4.0.18"
  "@vitest/expect": "^4.0.18"
  "ai": "^6.0.105"
  "es-toolkit": "^1.44.0"
  "tsup": "^8.5.1"
  "tsx": "^4.21.0"
  "vitest": "^4.0.18"
  "zod": "^4.3.6"