packages:
  - 'apps/*'
  - 'packages/*'
  - 'tools/*'

catalog:
  '@ai-sdk/anthropic': '^3.0.81'
  '@ai-sdk/google': '^3.0.80'
  '@ai-sdk/openai': '^3.0.68'
  '@ai-sdk/openai-compatible': '^2.0.48'
  '@ai-sdk/togetherai': '^2.0.53'
  '@vitest/coverage-v8': '^4.1.8'
  '@vitest/expect': '^4.1.8'
  'ai': '^6.0.197'
  'ai-sdk-ollama': '^3.8.6'
  'es-toolkit': '^1.47.0'
  'tsup': '^8.5.1'
  'tsx': '^4.21.0'
  'vitest': '^4.1.8'
  'zod': '^4.4.3'
