name: "Bug report"
description: "Report a bug to help us improve"
title: "bug: <short description>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a bug report!
        If this is a security-related vulnerability, please do NOT open a public issue. Follow SECURITY.md instead.
  - type: input
    id: version
    attributes:
      label: Package version
      description: Version of @heripo packages (e.g., 0.1.0)
      placeholder: 0.1.0
    validations:
      required: true
  - type: input
    id: node
    attributes:
      label: Node.js version
      placeholder: 22.x / 24.x
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      render: bash
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Other
    validations:
      required: true
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: I am not reporting a security vulnerability (see SECURITY.md)
          required: true
        - label: I have searched existing issues
          required: true
