name: "Feature request"
description: "Suggest a new feature or enhancement"
title: "feat: <short description>"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea clearly.
  - type: dropdown
    id: package
    attributes:
      label: Affected Package(s)
      options:
        - "@heripo/pdf-parser"
        - "@heripo/document-processor"
        - "@heripo/model"
        - "demo-web"
        - "Other"
      multiple: true
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? (e.g., "I'm frustrated when...")
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature or enhancement you'd like to see.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered?
    validations:
      required: false
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: I have searched existing issues
          required: true
